name: design_system
description: "A new Flutter package project."
version: 0.0.1
homepage: none

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.1.2
  flutter_svg: ^2.0.10+1
  expandable: ^5.0.1
  dots_indicator: ^2.1.1
  step_progress_indicator: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/lotties/
    - assets/illustrations/

  fonts:
    - family: RussoOne
      fonts:
        - asset: lib/resources/fonts/russo/RussoOne-Regular.ttf

    - family: ChakraPetch
      fonts:
        - asset: lib/resources/fonts/chakra/ChakraPetch-Light.ttf
        - asset: lib/resources/fonts/chakra/ChakraPetch-Medium.ttf
        - asset: lib/resources/fonts/chakra/ChakraPetch-Bold.ttf
