name: design_system
description: "A new Flutter package project."
version: 0.0.1
homepage: none

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.1.2
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lotties/
    - assets/icons/

  fonts:
    - family: Lato
      fonts:
        - asset: lib/resources/fonts/lato/Lato-Light.ttf
        - asset: lib/resources/fonts/lato/Lato-Regular.ttf
        - asset: lib/resources/fonts/lato/Lato-Bold.ttf

    - family: Poppins
      fonts:
        - asset: lib/resources/fonts/poppins/Poppins-Light.ttf
        - asset: lib/resources/fonts/poppins/Poppins-Regular.ttf
        - asset: lib/resources/fonts/poppins/Poppins-Bold.ttf
